apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: maskafka
spec:
  kafka:
    version: 2.4.0
    authorization:
      type: simple
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "2"
    jvmOptions:
      -Xms: 3072m
      -Xmx: 3072m
    replicas: 3
    listeners:      
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: scram-sha-512
        networkPolicyPeers:
          - namespaceSelector: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
      log.retention.hours: 24
      log.retention.bytes: 1073741824
      log.segment.bytes: 268435456
      log.cleaner.enable: true
      log.cleanup.policy: delete
      auto.create.topics.enable: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kafka-block-storage
        size: 100Gi
        deleteClaim: true
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "0.5"
      limits:
        memory: 1Gi
        cpu: "1"
    jvmOptions:
      -Xms: 768m
      -Xmx: 768m
    storage:
      type: persistent-claim
      class: kafka-block-storage
      size: 10Gi
      deleteClaim: true
  entityOperator:
    userOperator: {}
